sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kndavidson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kndavidson/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-779252028801"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
